name: 'Validate'
on:
    push:
    workflow_dispatch:
    pull_request:
jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
              with:
                version: latest
            - uses: actions/setup-node@v4
              with:
                cache: 'pnpm'
            - run: pnpm install
            - run: pnpm compile
            - run: pnpm lint
